param (
  # If left empty, the script will auto-detect the version from python.exe
  [string]$Version = ""
)

$ErrorActionPreference = "Stop"

# Resolve absolute paths for msiexec compatibility
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$WorkspaceDir = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$PythonDir = Join-Path $WorkspaceDir "python"
$PythonExe = Join-Path $PythonDir "python.exe"
$TempDir = Join-Path $WorkspaceDir "temp_tcltk"
$MsiFile = Join-Path $WorkspaceDir "tcltk.msi"

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "      Portable Tkinter Automator v3      " -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# 1. Check if Python engine exists
if (-Not (Test-Path $PythonExe))
{
  Write-Host "[ERROR] Portable python.exe not found. Run bootstrap.ps1 first." -ForegroundColor Red
  Exit
}

# 2. Auto-detect version
if ($Version -eq "")
{
  Write-Host "[INFO] Auto-detecting Python version from engine..." -ForegroundColor DarkGray
  $Version = & $PythonExe -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')"

  if (-Not $Version)
  {
    Write-Host "[ERROR] Failed to detect version." -ForegroundColor Red
    Exit
  }
  Write-Host "[OK] Detected Version: $Version" -ForegroundColor Green
} else
{
  Write-Host "[INFO] Using user-specified version: $Version" -ForegroundColor Green
}

# 3. Download the specific tcltk.msi component from Python's FTP server
Write-Host "`n[INFO] Fetching Tkinter MSI installer directly from python.org..." -ForegroundColor Yellow
$MsiUrl = "https://www.python.org/ftp/python/$Version/amd64/tcltk.msi"

try
{
  Invoke-WebRequest -Uri $MsiUrl -OutFile $MsiFile
} catch
{
  Write-Host "[ERROR] Failed to download tcltk.msi. Verify network or version." -ForegroundColor Red
  Exit
}

# 4. Extract MSI Payload using native Windows tools
Write-Host "[INFO] Extracting MSI payload via msiexec (Administrative Install)..." -ForegroundColor Cyan
if (-Not (Test-Path $TempDir))
{ New-Item -ItemType Directory -Path $TempDir | Out-Null 
}

# msiexec /a performs a network/admin install (extracts files) without writing to the registry
$MsiProcess = Start-Process -FilePath "msiexec.exe" -ArgumentList "/a `"$MsiFile`" /qn TARGETDIR=`"$TempDir`"" -Wait -PassThru

if ($MsiProcess.ExitCode -ne 0)
{
  Write-Host "[ERROR] MSI extraction failed with exit code $($MsiProcess.ExitCode)" -ForegroundColor Red
  Exit
}

# Define source paths generated by the MSI extraction
$SrcTcl = Join-Path $TempDir "tcl"
$SrcTkinterModule = Join-Path $TempDir "Lib\tkinter"
$SrcDlls = Join-Path $TempDir "DLLs"
$DestSitePackages = Join-Path $PythonDir "Lib\site-packages"

# ---------------------------------------------------------
# Performing the "Organ Transplant"
# ---------------------------------------------------------
Write-Host "`n[INFO] Transplanting exact Tcl/Tk components..." -ForegroundColor Yellow

# Copy tcl folder
if (Test-Path $SrcTcl)
{
  Copy-Item -Path $SrcTcl -Destination $PythonDir -Recurse -Force
  Write-Host "  -> Transplanted 'tcl' runtime" -ForegroundColor Green
}

# Copy tkinter python module to site-packages
if (Test-Path $SrcTkinterModule)
{
  if (-Not (Test-Path $DestSitePackages))
  { New-Item -ItemType Directory -Path $DestSitePackages | Out-Null
  }
  Copy-Item -Path $SrcTkinterModule -Destination $DestSitePackages -Recurse -Force
  Write-Host "  -> Transplanted 'tkinter' python module" -ForegroundColor Green
}

# Copy essential DLLs and C-extensions
if (Test-Path $SrcDlls)
{
  $ExtractedDlls = Get-ChildItem -Path $SrcDlls -Filter "*.dll"
  $ExtractedPyds = Get-ChildItem -Path $SrcDlls -Filter "_tkinter.pyd"

  foreach ($file in ($ExtractedDlls + $ExtractedPyds))
  {
    Copy-Item -Path $file.FullName -Destination $PythonDir -Force
    Write-Host "  -> Transplanted $($file.Name)" -ForegroundColor Green
  }
}

# ---------------------------------------------------------
# Cleanup
# ---------------------------------------------------------
Write-Host "`n[INFO] Cleaning up temporary files..." -ForegroundColor DarkGray
Remove-Item -Path $TempDir -Recurse -Force
Remove-Item -Path $MsiFile -Force

Write-Host "`n[OK] Tkinter successfully added to the portable environment!" -ForegroundColor Green
Write-Host "NOTE: Remember to set `$env:TCL_LIBRARY and `$env:TK_LIBRARY in your activate.ps1/run.ps1" -ForegroundColor Cyan
Pause
